[package]
name = "sheatfish"
version = "0.4.0"
edition = "2021"
license = "MIT"
authors = ["cadecraft"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
homedir = "0.3.4"
